

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
spring.cloud.openfeign.okhttp.enabled=true

# Server
server.port=${PORT:8080}

telegram.bot-username=${TELEGRAM_BOT_USERNAME}
telegram.bot-token=${TELEGRAM_BOT_TOKEN}